# Q-Learning Example by Code python 

In [ ]:
# source: http://mnemstudio.org/path-finding-q-learning-tutorial.htm

In [114]:
#import all dependencies
import numpy as np
import matplotlib.pyplot as plt
import random as random
from skimage import io
%matplotlib inline

In [27]:
# initilize matrix Q as a zero matirx
Q=np.zeros(36).reshape(6,6)
Q

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
# Create a Reward State and Action state corresponding to rows 
#and columns representation Action of that state change

R=np.zeros(36).reshape(6,6)
# first make all value 0 by default and change to -1 all of them
for i in range(6):
    for j in range(6):
        R[i][j]=-1

In [29]:
# now put some reward
R[0,4]=0
R[1,3]=0
R[1,5]=100
R[2,3]=0
R[3,1]=0
R[3,2]=0
R[3,4]=0
R[4,0]=0
R[4,3]=0
R[4,5]=100
R[5,1]=0
R[5,4]=0
R[5,5]=100

# final Reward Matrix
R

array([[  -1.,   -1.,   -1.,   -1.,    0.,   -1.],
       [  -1.,   -1.,   -1.,    0.,   -1.,  100.],
       [  -1.,   -1.,   -1.,    0.,   -1.,   -1.],
       [  -1.,    0.,    0.,   -1.,    0.,   -1.],
       [   0.,   -1.,   -1.,    0.,   -1.,  100.],
       [  -1.,    0.,   -1.,   -1.,    0.,  100.]])

In [30]:
# set a hyper parameter gamma
gamma=0.8 # hyper parameter

In [31]:
def Q_state(Q,R,gamma,state):
    possible_actions=[]
    for i in range(6):
        if(R[state,i])>=0:
            possible_actions.append(i)
    action=random.choice(possible_actions)
    temp=[]
    for i in range(6):
        if(R[action,i])>=0:
            temp.append(Q[action,i])
    max_reward=max(temp)
    Q[state,action]=R[state,action]+gamma*max_reward
    return action

In [32]:
episode=10000
goal_state=5
for i in range(episode):
    current_state=random.randint(0,5)
    while True:
        next_state=Q_state(Q,R,gamma,current_state)
        current_state=next_state
        if(current_state==goal_state):
             break

In [33]:
# normalize the Q matrix with the highest value and multiply with 100
def Q_normalize(Q):
    max_val=np.max(Q)
    return np.multiply((np.divide(Q,max_val)),100)

In [34]:
Q_normalize(Q) # this is the our agent memory

array([[   0. ,    0. ,    0. ,    0. ,   80. ,    0. ],
       [   0. ,    0. ,    0. ,   64. ,    0. ,  100. ],
       [   0. ,    0. ,    0. ,   64. ,    0. ,    0. ],
       [   0. ,   80. ,   51.2,    0. ,   80. ,    0. ],
       [  64. ,    0. ,    0. ,   64. ,    0. ,  100. ],
       [   0. ,   80. ,    0. ,    0. ,   80. ,  100. ]])

In [156]:
# Once the Q matrix gets closed enough to a state of convergence, we know our agent has learned 
# the most optimal path to the goal state. Tacing the best sequence of state is as
# simple as following the links the highest values at each state

mem=Q_normalize(Q)
def Find_path(initial_state,goal_state):
    path=[]
    path.append(initial_state)
    while True:
        t=max(mem[initial_state])
        c=np.where(mem[initial_state]==t)
        x=np.squeeze(c)
        try:
            temp_path=x[0]
        except (IndexError):
            temp_path=np.max(x)
        initial_state=temp_path
        path.append(temp_path)
        if(initial_state==goal):
             break
    return path

In [158]:
# suppose that our agent in room 2 and tries to go in room no 5
Find_path(2,5)

[2, 3, 1, 5]